import chalk from "chalk";
import fs from "node:fs";
import path from "node:path";

/**
 * Generates the aggregator TypeScript file that imports all translation JSON files
 * and exports them as a single messages object.
 */
export function generateAggregator(
  messagesDir: string,
  outputDir?: string
): void {
  const baseMessagesDir = path.resolve(messagesDir);

  if (!fs.existsSync(baseMessagesDir)) {
    console.log(chalk.yellow("⚠️  Messages directory does not exist, skipping aggregator generation"));
    return;
  }

  // Scan for locales and namespaces
  const locales = fs
    .readdirSync(baseMessagesDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .sort();

  if (locales.length === 0) {
    console.log(chalk.yellow("⚠️  No locale directories found, skipping aggregator generation"));
    return;
  }

  // Collect all JSON files organized by locale
  const filesByLocale = new Map<string, string[]>();

  for (const locale of locales) {
    const localeDir = path.join(baseMessagesDir, locale);
    const files = fs
      .readdirSync(localeDir)
      .filter((file) => file.endsWith(".json"))
      .sort();

    if (files.length > 0) {
      filesByLocale.set(locale, files);
    }
  }

  if (filesByLocale.size === 0) {
    console.log(chalk.yellow("⚠️  No JSON files found, skipping aggregator generation"));
    return;
  }

  // Generate imports and exports
  const imports: string[] = [];
  const exportsByLocale = new Map<string, string[]>();

  for (const [locale, files] of filesByLocale) {
    const localeExports: string[] = [];

    for (const file of files) {
      const namespace = path.basename(file, ".json");
      const importName = `${namespace}_${locale}`;
      const relativePath = `../messages/${locale}/${file}`;

      imports.push(`import ${importName} from "${relativePath}";`);
      localeExports.push(`    ...${importName},`);
    }

    exportsByLocale.set(locale, localeExports);
  }

  // Build the output content
  const lines: string[] = [
    "/**",
    " * Auto-generated aggregator file.",
    " * DO NOT EDIT MANUALLY - This file is regenerated by i18nizer.",
    " */",
    "",
    ...imports,
    "",
    "export const messages = {",
  ];

  for (const [locale, exports] of exportsByLocale) {
    lines.push(`  ${locale}: {`);
    lines.push(...exports);
    lines.push("  },");
  }

  lines.push("} as const;");
  lines.push("");

  // Write the file
  const i18nDir = outputDir ?? path.join(path.dirname(baseMessagesDir), "i18n");
  fs.mkdirSync(i18nDir, { recursive: true });

  const outputPath = path.join(i18nDir, "messages.generated.ts");
  fs.writeFileSync(outputPath, lines.join("\n"), "utf8");

  console.log(chalk.green(`✨ Aggregator generated: ${outputPath}`));

  // Log statistics
  const namespaces = new Set<string>();
  for (const files of filesByLocale.values()) {
    for (const file of files) {
      namespaces.add(path.basename(file, ".json"));
    }
  }

  console.log(chalk.cyan(`📦 Processed ${locales.length} locales, ${namespaces.size} namespaces`));
}
