import chalk from "chalk";
import fs from "node:fs";
import path from "node:path";

import { filenameToIdentifier } from "./filename-utils.js";

/**
 * Generates the aggregator TypeScript file that imports all translation JSON files
 * and exports them as a single messages object.
 */
export function generateAggregator(
  messagesDir: string,
  outputDir?: string
): void {
  const baseMessagesDir = path.resolve(messagesDir);

  if (!fs.existsSync(baseMessagesDir)) {
    console.log(chalk.yellow("⚠️  Messages directory does not exist, skipping aggregator generation"));
    return;
  }

  // Scan for locales and namespaces
  const locales = fs
    .readdirSync(baseMessagesDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .sort();

  if (locales.length === 0) {
    console.log(chalk.yellow("⚠️  No locale directories found, skipping aggregator generation"));
    return;
  }

  // Recursively collect all JSON files organized by locale
  const filesByLocale = new Map<string, Array<{ filename: string; relativePath: string }>>();

  /**
   * Recursively find all JSON files in a directory
   */
  function findJsonFiles(dir: string, baseDir: string): Array<{ filename: string; relativePath: string }> {
    const results: Array<{ filename: string; relativePath: string }> = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      
      if (entry.isDirectory()) {
        // Recursively scan subdirectories
        results.push(...findJsonFiles(fullPath, baseDir));
      } else if (entry.isFile() && entry.name.endsWith(".json")) {
        // Get relative path from the base locale directory
        const relativePath = path.relative(baseDir, fullPath);
        results.push({ filename: entry.name, relativePath });
      }
    }

    return results;
  }

  for (const locale of locales) {
    const localeDir = path.join(baseMessagesDir, locale);
    const files = findJsonFiles(localeDir, localeDir).sort((a, b) => 
      a.relativePath.localeCompare(b.relativePath)
    );

    if (files.length > 0) {
      filesByLocale.set(locale, files);
    }
  }

  if (filesByLocale.size === 0) {
    console.log(chalk.yellow("⚠️  No JSON files found, skipping aggregator generation"));
    return;
  }

  // Generate imports and exports
  const imports: string[] = [];
  const exportsByLocale = new Map<string, string[]>();

  for (const [locale, files] of filesByLocale) {
    const localeExports: string[] = [];

    for (const fileInfo of files) {
      const namespace = path.basename(fileInfo.filename, ".json");
      // Convert filename to valid TypeScript identifier (kebab-case to PascalCase)
      const identifier = filenameToIdentifier(namespace);
      
      // Create unique import name including subdirectory path to avoid conflicts
      // Replace path separators with underscores and sanitize
      const pathPrefix = path.dirname(fileInfo.relativePath)
        .split(path.sep)
        .filter((part) => part !== ".")
        .map((part) => filenameToIdentifier(part))
        .join("");
      
      const importName = pathPrefix 
        ? `${pathPrefix}_${identifier}_${locale}`
        : `${identifier}_${locale}`;
      
      const relativePath = `../messages/${locale}/${fileInfo.relativePath.split(path.sep).join("/")}`;

      imports.push(`import ${importName} from "${relativePath}";`);
      localeExports.push(`    ...${importName},`);
    }

    exportsByLocale.set(locale, localeExports);
  }

  // Build the output content
  const lines: string[] = [
    "/**",
    " * Auto-generated aggregator file.",
    " * DO NOT EDIT MANUALLY - This file is regenerated by i18nizer.",
    " */",
    "",
    ...imports,
    "",
    "export const messages = {",
  ];

  for (const [locale, exports] of exportsByLocale) {
    lines.push(`  ${locale}: {`, ...exports, "  },");
  }

  lines.push("} as const;", "");

  // Write the file
  const i18nDir = outputDir ?? path.join(path.dirname(baseMessagesDir), "i18n");
  fs.mkdirSync(i18nDir, { recursive: true });

  const outputPath = path.join(i18nDir, "messages.generated.ts");
  fs.writeFileSync(outputPath, lines.join("\n"), "utf8");

  console.log(chalk.green(`✨ Aggregator generated: ${outputPath}`));

  // Log statistics
  const namespaces = new Set<string>();
  for (const files of filesByLocale.values()) {
    for (const fileInfo of files) {
      namespaces.add(path.basename(fileInfo.filename, ".json"));
    }
  }

  console.log(chalk.cyan(`📦 Processed ${locales.length} locales, ${namespaces.size} namespaces`));
}
